server:
  port: 8080

spring:

  application:
    name: store

  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true